<?php

namespace BabyFootBundle\Repository;

/**
 * TestERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestERepository extends \Doctrine\ORM\EntityRepository
{
}
