<?php

namespace BabyFootBundle\Repository;

/**
 * TournamentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TournamentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findTournamentsByDate($date)
    {
	$query = $this->_em->createQuery('SELECT * FROM tournament WHERE begining_date => :date');
	$query->setParameters('date', $date);
	return $query->getResult();
    }

    public function findPlayerByTournament($id)
    {
	$query = $this->createQueryBuilder('tour');
	$query->select('tour.id')
			->leftjoin('tour.teams','tt')
			->addSelect('tt.name')
			->leftjoin('tt.players', 'p')
			->addSelect('p.name')
			->where('tour.id=:id');
	$query->setParameter('id', $id);
	$result = $query->getQuery()
			->getResult();
	return $result;
   }

}
